[package]
name = "windowdeck-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
windowdeck-diagnostics = { path = "../windowdeck-diagnostics" }
windowdeck-protocol = { path = "../windowdeck-protocol" }

[lints]
workspace = true
